/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedFlashcardsIndexRouteImport } from './routes/_authenticated/flashcards/index'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams/index'
import { Route as AuthenticatedFlashcardsNewRouteImport } from './routes/_authenticated/flashcards/new'
import { Route as AuthenticatedExamsNewRouteImport } from './routes/_authenticated/exams/new'
import { Route as AuthenticatedFlashcardsDeckIdIndexRouteImport } from './routes/_authenticated/flashcards/$deckId/index'
import { Route as AuthenticatedExamsExamIdIndexRouteImport } from './routes/_authenticated/exams/$examId/index'
import { Route as AuthenticatedFlashcardsDeckIdStudyRouteImport } from './routes/_authenticated/flashcards/$deckId/study'
import { Route as AuthenticatedExamsExamIdStartRouteImport } from './routes/_authenticated/exams/$examId/start'
import { Route as AuthenticatedExamsExamIdResultsRouteImport } from './routes/_authenticated/exams/$examId/results'
import { Route as AuthenticatedExamsExamIdResultsIndexRouteImport } from './routes/_authenticated/exams/$examId/results/index'
import { Route as AuthenticatedExamsExamIdResultsPendingRouteImport } from './routes/_authenticated/exams/$examId/results/pending'
import { Route as AuthenticatedExamsExamIdResultsErrorRouteImport } from './routes/_authenticated/exams/$examId/results/error'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlashcardsIndexRoute =
  AuthenticatedFlashcardsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFlashcardsRoute,
  } as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedExamsRoute,
} as any)
const AuthenticatedFlashcardsNewRoute =
  AuthenticatedFlashcardsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedFlashcardsRoute,
  } as any)
const AuthenticatedExamsNewRoute = AuthenticatedExamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedExamsRoute,
} as any)
const AuthenticatedFlashcardsDeckIdIndexRoute =
  AuthenticatedFlashcardsDeckIdIndexRouteImport.update({
    id: '/$deckId/',
    path: '/$deckId/',
    getParentRoute: () => AuthenticatedFlashcardsRoute,
  } as any)
const AuthenticatedExamsExamIdIndexRoute =
  AuthenticatedExamsExamIdIndexRouteImport.update({
    id: '/$examId/',
    path: '/$examId/',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedFlashcardsDeckIdStudyRoute =
  AuthenticatedFlashcardsDeckIdStudyRouteImport.update({
    id: '/$deckId/study',
    path: '/$deckId/study',
    getParentRoute: () => AuthenticatedFlashcardsRoute,
  } as any)
const AuthenticatedExamsExamIdStartRoute =
  AuthenticatedExamsExamIdStartRouteImport.update({
    id: '/$examId/start',
    path: '/$examId/start',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedExamsExamIdResultsRoute =
  AuthenticatedExamsExamIdResultsRouteImport.update({
    id: '/$examId/results',
    path: '/$examId/results',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedExamsExamIdResultsIndexRoute =
  AuthenticatedExamsExamIdResultsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExamsExamIdResultsRoute,
  } as any)
const AuthenticatedExamsExamIdResultsPendingRoute =
  AuthenticatedExamsExamIdResultsPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedExamsExamIdResultsRoute,
  } as any)
const AuthenticatedExamsExamIdResultsErrorRoute =
  AuthenticatedExamsExamIdResultsErrorRouteImport.update({
    id: '/error',
    path: '/error',
    getParentRoute: () => AuthenticatedExamsExamIdResultsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/flashcards': typeof AuthenticatedFlashcardsRouteWithChildren
  '/exams/new': typeof AuthenticatedExamsNewRoute
  '/flashcards/new': typeof AuthenticatedFlashcardsNewRoute
  '/exams/': typeof AuthenticatedExamsIndexRoute
  '/flashcards/': typeof AuthenticatedFlashcardsIndexRoute
  '/exams/$examId/results': typeof AuthenticatedExamsExamIdResultsRouteWithChildren
  '/exams/$examId/start': typeof AuthenticatedExamsExamIdStartRoute
  '/flashcards/$deckId/study': typeof AuthenticatedFlashcardsDeckIdStudyRoute
  '/exams/$examId/': typeof AuthenticatedExamsExamIdIndexRoute
  '/flashcards/$deckId/': typeof AuthenticatedFlashcardsDeckIdIndexRoute
  '/exams/$examId/results/error': typeof AuthenticatedExamsExamIdResultsErrorRoute
  '/exams/$examId/results/pending': typeof AuthenticatedExamsExamIdResultsPendingRoute
  '/exams/$examId/results/': typeof AuthenticatedExamsExamIdResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/exams/new': typeof AuthenticatedExamsNewRoute
  '/flashcards/new': typeof AuthenticatedFlashcardsNewRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/flashcards': typeof AuthenticatedFlashcardsIndexRoute
  '/exams/$examId/start': typeof AuthenticatedExamsExamIdStartRoute
  '/flashcards/$deckId/study': typeof AuthenticatedFlashcardsDeckIdStudyRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdIndexRoute
  '/flashcards/$deckId': typeof AuthenticatedFlashcardsDeckIdIndexRoute
  '/exams/$examId/results/error': typeof AuthenticatedExamsExamIdResultsErrorRoute
  '/exams/$examId/results/pending': typeof AuthenticatedExamsExamIdResultsPendingRoute
  '/exams/$examId/results': typeof AuthenticatedExamsExamIdResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRouteWithChildren
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRouteWithChildren
  '/_authenticated/exams/new': typeof AuthenticatedExamsNewRoute
  '/_authenticated/flashcards/new': typeof AuthenticatedFlashcardsNewRoute
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
  '/_authenticated/flashcards/': typeof AuthenticatedFlashcardsIndexRoute
  '/_authenticated/exams/$examId/results': typeof AuthenticatedExamsExamIdResultsRouteWithChildren
  '/_authenticated/exams/$examId/start': typeof AuthenticatedExamsExamIdStartRoute
  '/_authenticated/flashcards/$deckId/study': typeof AuthenticatedFlashcardsDeckIdStudyRoute
  '/_authenticated/exams/$examId/': typeof AuthenticatedExamsExamIdIndexRoute
  '/_authenticated/flashcards/$deckId/': typeof AuthenticatedFlashcardsDeckIdIndexRoute
  '/_authenticated/exams/$examId/results/error': typeof AuthenticatedExamsExamIdResultsErrorRoute
  '/_authenticated/exams/$examId/results/pending': typeof AuthenticatedExamsExamIdResultsPendingRoute
  '/_authenticated/exams/$examId/results/': typeof AuthenticatedExamsExamIdResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/exams'
    | '/flashcards'
    | '/exams/new'
    | '/flashcards/new'
    | '/exams/'
    | '/flashcards/'
    | '/exams/$examId/results'
    | '/exams/$examId/start'
    | '/flashcards/$deckId/study'
    | '/exams/$examId/'
    | '/flashcards/$deckId/'
    | '/exams/$examId/results/error'
    | '/exams/$examId/results/pending'
    | '/exams/$examId/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/exams/new'
    | '/flashcards/new'
    | '/exams'
    | '/flashcards'
    | '/exams/$examId/start'
    | '/flashcards/$deckId/study'
    | '/exams/$examId'
    | '/flashcards/$deckId'
    | '/exams/$examId/results/error'
    | '/exams/$examId/results/pending'
    | '/exams/$examId/results'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/exams'
    | '/_authenticated/flashcards'
    | '/_authenticated/exams/new'
    | '/_authenticated/flashcards/new'
    | '/_authenticated/exams/'
    | '/_authenticated/flashcards/'
    | '/_authenticated/exams/$examId/results'
    | '/_authenticated/exams/$examId/start'
    | '/_authenticated/flashcards/$deckId/study'
    | '/_authenticated/exams/$examId/'
    | '/_authenticated/flashcards/$deckId/'
    | '/_authenticated/exams/$examId/results/error'
    | '/_authenticated/exams/$examId/results/pending'
    | '/_authenticated/exams/$examId/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards/': {
      id: '/_authenticated/flashcards/'
      path: '/'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof AuthenticatedFlashcardsIndexRouteImport
      parentRoute: typeof AuthenticatedFlashcardsRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/flashcards/new': {
      id: '/_authenticated/flashcards/new'
      path: '/new'
      fullPath: '/flashcards/new'
      preLoaderRoute: typeof AuthenticatedFlashcardsNewRouteImport
      parentRoute: typeof AuthenticatedFlashcardsRoute
    }
    '/_authenticated/exams/new': {
      id: '/_authenticated/exams/new'
      path: '/new'
      fullPath: '/exams/new'
      preLoaderRoute: typeof AuthenticatedExamsNewRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/flashcards/$deckId/': {
      id: '/_authenticated/flashcards/$deckId/'
      path: '/$deckId'
      fullPath: '/flashcards/$deckId/'
      preLoaderRoute: typeof AuthenticatedFlashcardsDeckIdIndexRouteImport
      parentRoute: typeof AuthenticatedFlashcardsRoute
    }
    '/_authenticated/exams/$examId/': {
      id: '/_authenticated/exams/$examId/'
      path: '/$examId'
      fullPath: '/exams/$examId/'
      preLoaderRoute: typeof AuthenticatedExamsExamIdIndexRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/flashcards/$deckId/study': {
      id: '/_authenticated/flashcards/$deckId/study'
      path: '/$deckId/study'
      fullPath: '/flashcards/$deckId/study'
      preLoaderRoute: typeof AuthenticatedFlashcardsDeckIdStudyRouteImport
      parentRoute: typeof AuthenticatedFlashcardsRoute
    }
    '/_authenticated/exams/$examId/start': {
      id: '/_authenticated/exams/$examId/start'
      path: '/$examId/start'
      fullPath: '/exams/$examId/start'
      preLoaderRoute: typeof AuthenticatedExamsExamIdStartRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/exams/$examId/results': {
      id: '/_authenticated/exams/$examId/results'
      path: '/$examId/results'
      fullPath: '/exams/$examId/results'
      preLoaderRoute: typeof AuthenticatedExamsExamIdResultsRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/exams/$examId/results/': {
      id: '/_authenticated/exams/$examId/results/'
      path: '/'
      fullPath: '/exams/$examId/results/'
      preLoaderRoute: typeof AuthenticatedExamsExamIdResultsIndexRouteImport
      parentRoute: typeof AuthenticatedExamsExamIdResultsRoute
    }
    '/_authenticated/exams/$examId/results/pending': {
      id: '/_authenticated/exams/$examId/results/pending'
      path: '/pending'
      fullPath: '/exams/$examId/results/pending'
      preLoaderRoute: typeof AuthenticatedExamsExamIdResultsPendingRouteImport
      parentRoute: typeof AuthenticatedExamsExamIdResultsRoute
    }
    '/_authenticated/exams/$examId/results/error': {
      id: '/_authenticated/exams/$examId/results/error'
      path: '/error'
      fullPath: '/exams/$examId/results/error'
      preLoaderRoute: typeof AuthenticatedExamsExamIdResultsErrorRouteImport
      parentRoute: typeof AuthenticatedExamsExamIdResultsRoute
    }
  }
}

interface AuthenticatedExamsExamIdResultsRouteChildren {
  AuthenticatedExamsExamIdResultsErrorRoute: typeof AuthenticatedExamsExamIdResultsErrorRoute
  AuthenticatedExamsExamIdResultsPendingRoute: typeof AuthenticatedExamsExamIdResultsPendingRoute
  AuthenticatedExamsExamIdResultsIndexRoute: typeof AuthenticatedExamsExamIdResultsIndexRoute
}

const AuthenticatedExamsExamIdResultsRouteChildren: AuthenticatedExamsExamIdResultsRouteChildren =
  {
    AuthenticatedExamsExamIdResultsErrorRoute:
      AuthenticatedExamsExamIdResultsErrorRoute,
    AuthenticatedExamsExamIdResultsPendingRoute:
      AuthenticatedExamsExamIdResultsPendingRoute,
    AuthenticatedExamsExamIdResultsIndexRoute:
      AuthenticatedExamsExamIdResultsIndexRoute,
  }

const AuthenticatedExamsExamIdResultsRouteWithChildren =
  AuthenticatedExamsExamIdResultsRoute._addFileChildren(
    AuthenticatedExamsExamIdResultsRouteChildren,
  )

interface AuthenticatedExamsRouteChildren {
  AuthenticatedExamsNewRoute: typeof AuthenticatedExamsNewRoute
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
  AuthenticatedExamsExamIdResultsRoute: typeof AuthenticatedExamsExamIdResultsRouteWithChildren
  AuthenticatedExamsExamIdStartRoute: typeof AuthenticatedExamsExamIdStartRoute
  AuthenticatedExamsExamIdIndexRoute: typeof AuthenticatedExamsExamIdIndexRoute
}

const AuthenticatedExamsRouteChildren: AuthenticatedExamsRouteChildren = {
  AuthenticatedExamsNewRoute: AuthenticatedExamsNewRoute,
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
  AuthenticatedExamsExamIdResultsRoute:
    AuthenticatedExamsExamIdResultsRouteWithChildren,
  AuthenticatedExamsExamIdStartRoute: AuthenticatedExamsExamIdStartRoute,
  AuthenticatedExamsExamIdIndexRoute: AuthenticatedExamsExamIdIndexRoute,
}

const AuthenticatedExamsRouteWithChildren =
  AuthenticatedExamsRoute._addFileChildren(AuthenticatedExamsRouteChildren)

interface AuthenticatedFlashcardsRouteChildren {
  AuthenticatedFlashcardsNewRoute: typeof AuthenticatedFlashcardsNewRoute
  AuthenticatedFlashcardsIndexRoute: typeof AuthenticatedFlashcardsIndexRoute
  AuthenticatedFlashcardsDeckIdStudyRoute: typeof AuthenticatedFlashcardsDeckIdStudyRoute
  AuthenticatedFlashcardsDeckIdIndexRoute: typeof AuthenticatedFlashcardsDeckIdIndexRoute
}

const AuthenticatedFlashcardsRouteChildren: AuthenticatedFlashcardsRouteChildren =
  {
    AuthenticatedFlashcardsNewRoute: AuthenticatedFlashcardsNewRoute,
    AuthenticatedFlashcardsIndexRoute: AuthenticatedFlashcardsIndexRoute,
    AuthenticatedFlashcardsDeckIdStudyRoute:
      AuthenticatedFlashcardsDeckIdStudyRoute,
    AuthenticatedFlashcardsDeckIdIndexRoute:
      AuthenticatedFlashcardsDeckIdIndexRoute,
  }

const AuthenticatedFlashcardsRouteWithChildren =
  AuthenticatedFlashcardsRoute._addFileChildren(
    AuthenticatedFlashcardsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRouteWithChildren
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRouteWithChildren,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
